### ISSUE TITLE
Samurai timeline issue

### ISSUE THREAD

**Issue by HySyHyFy** [Tischel/ActionTimeline#6]
There's an issue with the timeline for samurais when using Kaeshi: Namikiri it appears as red like you're missing/clipping a gcd, but it's an instant cast. 
![image](https://github.com/Tischel/ActionTimeline/assets/29317946/f1ab207c-609e-4897-9545-cec22e2aaa67)

**Comment by Tischel** [comment]
Fixed in v1.3.0.1
